import { DsUtilitiesBase } from "../base/DsUtilitiesBase";
import { getDsId } from "./functions/structure/getDsId.fn";
import { getDsName } from "./functions/ui/getDsName.fn";
import { getDsRootNode } from "./functions/structure/getDsRootNode.fn";
import { getDsStandardContext } from "./functions/structure/getDsStandardContext.fn";
import { getDsDescription } from "./functions/ui/getDsDescription.fn";
import { getDsAuthorName } from "./functions/ui/getDsAuthorName.fn";
import { getDsSchemaVersion } from "./functions/ui/getDsSchemaVersion.fn";
import { getDsVersion } from "./functions/ui/getDsVersion.fn";
import { getDsExternalVocabularies } from "./functions/ui/getDsExternalVocabularies.fn";
import { getDsTargetClasses } from "./functions/ui/getDsTargetClasses.fn";
import { generateInnerNodeId } from "./functions/structure/generateInnerNodeId.fn";
import { reorderDsNode } from "./functions/structure/reorderDsNode.fn";
import { identifyDsGrammarNodeType } from "./functions/structure/identifyDsGrammarNodeType.fn";
import { dsPathGetNode } from "./functions/path/dsPathGetNode.fn";
import { reorderDs } from "./functions/structure/reorderDs.fn";
import { getDataTypeLabel } from "./functions/ui/getDataTypeLabel.fn";
import { getDsDataTypeForSchemaDataType } from "./functions/structure/getDsDataTypeForSchemaDataType.fn";
import { getSchemaDataTypeForDsDataType } from "./functions/structure/getSchemaDataTypeForDsDataType.fn";
import { dsPathInit } from "./functions/path/dsPathInit.fn";
import { dsPathAddition } from "./functions/path/dsPathAddition.fn";
import { dsPathIdentifyNodeType } from "./functions/path/dsPathIdentifyNodeType.fn";
import { tokenizeDsPath } from "./functions/path/tokenizeDsPath.fn";
import { verifyDs } from "./functions/verification/verifyDs.fn";
import { checkClassMatch } from "./functions/verification/checkClassMatch.fn";
export declare class DsUtilitiesV7 extends DsUtilitiesBase {
    protected dsUtilitiesVersion: string;
    constructor();
    getDsRootNode: typeof getDsRootNode;
    getDsStandardContext: typeof getDsStandardContext;
    getDsId: typeof getDsId;
    reorderDs: typeof reorderDs;
    reorderDsNode: typeof reorderDsNode;
    generateInnerNodeId: typeof generateInnerNodeId;
    getDsDataTypeForSchemaDataType: typeof getDsDataTypeForSchemaDataType;
    getSchemaDataTypeForDsDataType: typeof getSchemaDataTypeForDsDataType;
    identifyDsGrammarNodeType: typeof identifyDsGrammarNodeType;
    dsPathInit: typeof dsPathInit;
    dsPathAddition: typeof dsPathAddition;
    dsPathGetNode: typeof dsPathGetNode;
    dsPathIdentifyNodeType: typeof dsPathIdentifyNodeType;
    tokenizeDsPath: typeof tokenizeDsPath;
    getDsName: typeof getDsName;
    getDsDescription: typeof getDsDescription;
    getDsAuthorName: typeof getDsAuthorName;
    getDsSchemaVersion: typeof getDsSchemaVersion;
    getDsVersion: typeof getDsVersion;
    getDsExternalVocabularies: typeof getDsExternalVocabularies;
    getDsTargetClasses: typeof getDsTargetClasses;
    getDataTypeLabel: typeof getDataTypeLabel;
    verifyDs: typeof verifyDs;
    checkClassMatch: typeof checkClassMatch;
}
//# sourceMappingURL=DsUtilitiesV7.d.ts.map