"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.DsUtilitiesV7 = void 0;
const DsUtilitiesBase_1 = require("../base/DsUtilitiesBase");
const getDsId_fn_1 = require("./functions/structure/getDsId.fn");
const getDsName_fn_1 = require("./functions/ui/getDsName.fn");
const getDsRootNode_fn_1 = require("./functions/structure/getDsRootNode.fn");
const getDsStandardContext_fn_1 = require("./functions/structure/getDsStandardContext.fn");
const getDsDescription_fn_1 = require("./functions/ui/getDsDescription.fn");
const getDsAuthorName_fn_1 = require("./functions/ui/getDsAuthorName.fn");
const getDsSchemaVersion_fn_1 = require("./functions/ui/getDsSchemaVersion.fn");
const getDsVersion_fn_1 = require("./functions/ui/getDsVersion.fn");
const getDsExternalVocabularies_fn_1 = require("./functions/ui/getDsExternalVocabularies.fn");
const getDsTargetClasses_fn_1 = require("./functions/ui/getDsTargetClasses.fn");
const generateInnerNodeId_fn_1 = require("./functions/structure/generateInnerNodeId.fn");
const reorderDsNode_fn_1 = require("./functions/structure/reorderDsNode.fn");
const identifyDsGrammarNodeType_fn_1 = require("./functions/structure/identifyDsGrammarNodeType.fn");
const dsPathGetNode_fn_1 = require("./functions/path/dsPathGetNode.fn");
const reorderDs_fn_1 = require("./functions/structure/reorderDs.fn");
const getDataTypeLabel_fn_1 = require("./functions/ui/getDataTypeLabel.fn");
const getDsDataTypeForSchemaDataType_fn_1 = require("./functions/structure/getDsDataTypeForSchemaDataType.fn");
const getSchemaDataTypeForDsDataType_fn_1 = require("./functions/structure/getSchemaDataTypeForDsDataType.fn");
const dsPathInit_fn_1 = require("./functions/path/dsPathInit.fn");
const dsPathAddition_fn_1 = require("./functions/path/dsPathAddition.fn");
const dsPathIdentifyNodeType_fn_1 = require("./functions/path/dsPathIdentifyNodeType.fn");
const tokenizeDsPath_fn_1 = require("./functions/path/tokenizeDsPath.fn");
const verifyDs_fn_1 = require("./functions/verification/verifyDs.fn");
const checkClassMatch_fn_1 = require("./functions/verification/checkClassMatch.fn");
class DsUtilitiesV7 extends DsUtilitiesBase_1.DsUtilitiesBase {
    constructor() {
        super();
        this.dsUtilitiesVersion = "7.0";
        this.getDsRootNode = getDsRootNode_fn_1.getDsRootNode;
        this.getDsStandardContext = getDsStandardContext_fn_1.getDsStandardContext;
        this.getDsId = getDsId_fn_1.getDsId;
        this.reorderDs = reorderDs_fn_1.reorderDs;
        this.reorderDsNode = reorderDsNode_fn_1.reorderDsNode;
        this.generateInnerNodeId = generateInnerNodeId_fn_1.generateInnerNodeId;
        this.getDsDataTypeForSchemaDataType = getDsDataTypeForSchemaDataType_fn_1.getDsDataTypeForSchemaDataType;
        this.getSchemaDataTypeForDsDataType = getSchemaDataTypeForDsDataType_fn_1.getSchemaDataTypeForDsDataType;
        this.identifyDsGrammarNodeType = identifyDsGrammarNodeType_fn_1.identifyDsGrammarNodeType;
        this.dsPathInit = dsPathInit_fn_1.dsPathInit;
        this.dsPathAddition = dsPathAddition_fn_1.dsPathAddition;
        this.dsPathGetNode = dsPathGetNode_fn_1.dsPathGetNode;
        this.dsPathIdentifyNodeType = dsPathIdentifyNodeType_fn_1.dsPathIdentifyNodeType;
        this.tokenizeDsPath = tokenizeDsPath_fn_1.tokenizeDsPath;
        this.getDsName = getDsName_fn_1.getDsName;
        this.getDsDescription = getDsDescription_fn_1.getDsDescription;
        this.getDsAuthorName = getDsAuthorName_fn_1.getDsAuthorName;
        this.getDsSchemaVersion = getDsSchemaVersion_fn_1.getDsSchemaVersion;
        this.getDsVersion = getDsVersion_fn_1.getDsVersion;
        this.getDsExternalVocabularies = getDsExternalVocabularies_fn_1.getDsExternalVocabularies;
        this.getDsTargetClasses = getDsTargetClasses_fn_1.getDsTargetClasses;
        this.getDataTypeLabel = getDataTypeLabel_fn_1.getDataTypeLabel;
        this.verifyDs = verifyDs_fn_1.verifyDs;
        this.checkClassMatch = checkClassMatch_fn_1.checkClassMatch;
    }
}
exports.DsUtilitiesV7 = DsUtilitiesV7;
//# sourceMappingURL=DsUtilitiesV7.js.map